# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x06sample\"&\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\x94\x02\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12%\n\x06gender\x18\x03 \x01(\x0e\x32\x15.sample.Person.Gender\x12!\n\x08\x66\x65\x61tures\x18\x04 \x03(\x0b\x32\x0f.sample.Feature\x12(\n\x05\x65xtra\x18\x05 \x03(\x0b\x32\x19.sample.Person.ExtraEntry\x12\r\n\x05token\x18\x06 \x01(\x0c\x12\r\n\x05\x61live\x18\x07 \x01(\x08\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x06Gender\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02\x62\x06proto3')



_FEATURE = DESCRIPTOR.message_types_by_name['Feature']
_PERSON = DESCRIPTOR.message_types_by_name['Person']
_PERSON_EXTRAENTRY = _PERSON.nested_types_by_name['ExtraEntry']
_PERSON_GENDER = _PERSON.enum_types_by_name['Gender']
Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.Feature)
  })
_sym_db.RegisterMessage(Feature)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'ExtraEntry' : _reflection.GeneratedProtocolMessageType('ExtraEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_EXTRAENTRY,
    '__module__' : 'sample_pb2'
    # @@protoc_insertion_point(class_scope:sample.Person.ExtraEntry)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:sample.Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.ExtraEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON_EXTRAENTRY._options = None
  _PERSON_EXTRAENTRY._serialized_options = b'8\001'
  _FEATURE._serialized_start=24
  _FEATURE._serialized_end=62
  _PERSON._serialized_start=65
  _PERSON._serialized_end=341
  _PERSON_EXTRAENTRY._serialized_start=248
  _PERSON_EXTRAENTRY._serialized_end=292
  _PERSON_GENDER._serialized_start=294
  _PERSON_GENDER._serialized_end=341
# @@protoc_insertion_point(module_scope)
