# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sample.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict, List

import betterproto


class PersonGender(betterproto.Enum):
    UNSPECIFIED = 0
    MALE = 1
    FEMALE = 2


@dataclass
class Feature(betterproto.Message):
    name: str = betterproto.string_field(1)
    value: float = betterproto.double_field(2)


@dataclass
class Person(betterproto.Message):
    name: str = betterproto.string_field(1)
    age: int = betterproto.int32_field(2)
    gender: "PersonGender" = betterproto.enum_field(3)
    features: List["Feature"] = betterproto.message_field(4)
    extra: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    token: bytes = betterproto.bytes_field(6)
    alive: bool = betterproto.bool_field(7)
